
project:
  type: website

website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - test_website.qmd
      - test_website_inteructive.qmd

engine: knitr
format:
  live-html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
